#![doc = "Peripheral access API for AST1080 microcontrollers (generated using svd2rust v0.36.1 (4052ce6 2025-04-04))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.36.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn spipf1();
    fn spipf2();
    fn spi();
    fn spi1();
    fn spi2();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 124] = [
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: spipf1 },
    Vector { _handler: spipf2 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: spi },
    Vector { _handler: spi1 },
    Vector { _handler: spi2 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "88 - spipf1"]
    spipf1 = 88,
    #[doc = "89 - spipf2"]
    spipf2 = 89,
    #[doc = "121 - spi"]
    spi = 121,
    #[doc = "122 - spi1"]
    spi1 = 122,
    #[doc = "123 - spi2"]
    spi2 = 123,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "spi"]
pub type Spi = crate::Periph<spi::RegisterBlock, 0x7400_0000>;
impl core::fmt::Debug for Spi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi").finish()
    }
}
#[doc = "spi"]
pub mod spi;
#[doc = "spi interface"]
pub type Spi1 = crate::Periph<spi::RegisterBlock, 0x7401_0000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "spi interface"]
pub use self::spi as spi1;
#[doc = "spi interface"]
pub type Spi2 = crate::Periph<spi::RegisterBlock, 0x7402_0000>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "spi interface"]
pub use self::spi as spi2;
#[doc = "sprot"]
pub type Sprot = crate::Periph<sprot::RegisterBlock, 0x7400_0800>;
impl core::fmt::Debug for Sprot {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sprot").finish()
    }
}
#[doc = "sprot"]
pub mod sprot;
#[doc = "sprot interface"]
pub type Sprot1 = crate::Periph<sprot::RegisterBlock, 0x7401_0800>;
impl core::fmt::Debug for Sprot1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sprot1").finish()
    }
}
#[doc = "sprot interface"]
pub use self::sprot as sprot1;
#[doc = "sprot interface"]
pub type Sprot2 = crate::Periph<sprot::RegisterBlock, 0x7402_0800>;
impl core::fmt::Debug for Sprot2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sprot2").finish()
    }
}
#[doc = "sprot interface"]
pub use self::sprot as sprot2;
#[doc = "spif"]
pub type Spif = crate::Periph<spif::RegisterBlock, 0x7400_0400>;
impl core::fmt::Debug for Spif {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spif").finish()
    }
}
#[doc = "spif"]
pub mod spif;
#[doc = "spipf"]
pub type Spipf = crate::Periph<spipf::RegisterBlock, 0x74c1_5000>;
impl core::fmt::Debug for Spipf {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spipf").finish()
    }
}
#[doc = "spipf"]
pub mod spipf;
#[doc = "spipf interface"]
pub type Spipf1 = crate::Periph<spipf::RegisterBlock, 0x74c1_6000>;
impl core::fmt::Debug for Spipf1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spipf1").finish()
    }
}
#[doc = "spipf interface"]
pub use self::spipf as spipf1;
#[doc = "spipf interface"]
pub type Spipf2 = crate::Periph<spipf::RegisterBlock, 0x74c1_7000>;
impl core::fmt::Debug for Spipf2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spipf2").finish()
    }
}
#[doc = "spipf interface"]
pub use self::spipf as spipf2;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "spi"]
    pub spi: Spi,
    #[doc = "spi1"]
    pub spi1: Spi1,
    #[doc = "spi2"]
    pub spi2: Spi2,
    #[doc = "sprot"]
    pub sprot: Sprot,
    #[doc = "sprot1"]
    pub sprot1: Sprot1,
    #[doc = "sprot2"]
    pub sprot2: Sprot2,
    #[doc = "spif"]
    pub spif: Spif,
    #[doc = "spipf"]
    pub spipf: Spipf,
    #[doc = "spipf1"]
    pub spipf1: Spipf1,
    #[doc = "spipf2"]
    pub spipf2: Spipf2,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            spi: Spi::steal(),
            spi1: Spi1::steal(),
            spi2: Spi2::steal(),
            sprot: Sprot::steal(),
            sprot1: Sprot1::steal(),
            sprot2: Sprot2::steal(),
            spif: Spif::steal(),
            spipf: Spipf::steal(),
            spipf1: Spipf1::steal(),
            spipf2: Spipf2::steal(),
        }
    }
}
